# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('week', models.DateField(default=django.utils.timezone.now)),
                ('allocated_hours', models.IntegerField(default=0)),
                ('actual_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=150)),
                ('holiday_date', models.DateField()),
                ('hours_lost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw_string', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pm_scope', models.IntegerField()),
                ('dev_scope', models.IntegerField()),
                ('design_scope', models.IntegerField()),
                ('testing_scope', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=150, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('weekly_copacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(choices=[(600, '6:00AM'), (630, '6:30AM'), (700, '7:00AM'), (730, '7:30AM'), (800, '8:00AM'), (830, '8:30AM'), (900, '9:00AM'), (930, '9:30AM'), (1000, '10:00AM'), (1030, '10:30AM'), (1100, '11:00AM'), (1130, '11:30AM'), (1200, '12:00PM'), (1230, '12:30PM'), (1300, '1:00PM'), (1330, '1:30PM'), (1400, '2:00PM'), (1430, '2:30PM'), (1500, '3:00PM'), (1530, '3:30PM'), (1600, '4:00PM'), (1630, '4:30PM'), (1700, '5:00PM'), (1730, '5:30PM'), (1800, '6:00PM'), (1830, '6:30PM')], default=800)),
                ('end_time', models.IntegerField(choices=[(600, '6:00AM'), (630, '6:30AM'), (700, '7:00AM'), (730, '7:30AM'), (800, '8:00AM'), (830, '8:30AM'), (900, '9:00AM'), (930, '9:30AM'), (1000, '10:00AM'), (1030, '10:30AM'), (1100, '11:00AM'), (1130, '11:30AM'), (1200, '12:00PM'), (1230, '12:30PM'), (1300, '1:00PM'), (1330, '1:30PM'), (1400, '2:00PM'), (1430, '2:30PM'), (1500, '3:00PM'), (1530, '3:30PM'), (1600, '4:00PM'), (1630, '4:30PM'), (1700, '5:00PM'), (1730, '5:30PM'), (1800, '6:00PM'), (1830, '6:30PM')], default=1700)),
                ('lunch', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=250)),
                ('setting_int', models.IntegerField(null=True)),
                ('setting_bool', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Time_Off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_lost', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Workdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Mon', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.Workdays'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.Resource_Type'),
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.User_Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.Project_Type'),
        ),
        migrations.AddField(
            model_name='passwords',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.Resource'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.Project'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity.Resource'),
        ),
    ]
