# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copacity', '0002_auto_20170802_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdays',
            name='Friday',
        ),
        migrations.RemoveField(
            model_name='workdays',
            name='Monday',
        ),
        migrations.RemoveField(
            model_name='workdays',
            name='Saturday',
        ),
        migrations.RemoveField(
            model_name='workdays',
            name='Sunday',
        ),
        migrations.RemoveField(
            model_name='workdays',
            name='Thursday',
        ),
        migrations.RemoveField(
            model_name='workdays',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='workdays',
            name='Wednesday',
        ),
        migrations.AddField(
            model_name='workdays',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workdays',
            name='day_name',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Mon', max_length=10),
        ),
    ]
