# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copacity', '0002_remove_allocation_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='week',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
