# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-06 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copacity', '0005_auto_20170802_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='actual_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allocation',
            name='allocated_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allocation',
            name='week',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
